export const subjects = [
  {
    id: "web",
    name: "Desarrollo de Aplicaciones Web",
    shortName: "Aplicaciones Web",
    credits: 3,
    color: "#0f766e",
    units: [
      "Programacion web en el cliente",
      "Programacion web en el servidor",
      "Microservicios y manejo de estados",
      "Control de versiones y DevOps",
    ],
  },
  {
    id: "redes",
    name: "Escalabilidad de Redes",
    shortName: "Redes",
    credits: 3,
    color: "#1d4ed8",
    units: [
      "Redes inalambricas",
      "Redes moviles, MPLS, SDN y NFV",
      "OSPF, STP, IS-IS y BGP",
      "Calidad de servicio QoS",
    ],
  },
  {
    id: "software",
    name: "Ingenieria de Software",
    shortName: "Ing. Software",
    credits: 3,
    color: "#7c3aed",
    units: [
      "Fundamentos de ingenieria de software",
      "Modelado de requerimientos",
      "Analisis y documentacion",
      "Metodologias agiles",
      "Diseno de software",
    ],
  },
  {
    id: "mineria",
    name: "Mineria de Datos",
    shortName: "Mineria",
    credits: 3,
    color: "#b45309",
    units: [
      "Proceso KDD y preparacion de datos",
      "Mineria predictiva",
      "Mineria descriptiva",
      "Texto, redes sociales y datos espaciales",
    ],
  },
  {
    id: "embebidos",
    name: "Sistemas Embebidos",
    shortName: "Embebidos",
    credits: 3,
    color: "#be123c",
    units: [
      "Fundamentos de sistemas embebidos",
      "Hardware embebido",
      "Software embebido",
      "Comunicacion y aplicaciones",
    ],
  },
];

const webQuestions = [
  {
    subjectId: "web",
    unit: 1,
    difficulty: "facil",
    question: "En una aplicacion web, cual es la funcion principal de HTML?",
    options: [
      "Definir la estructura semantica del contenido que se mostrara en el navegador.",
      "Ejecutar consultas directamente sobre la base de datos del servidor.",
      "Administrar el despliegue continuo de la aplicacion.",
      "Controlar el versionamiento del codigo fuente.",
    ],
    answer: 0,
    explanation: "HTML organiza el contenido y su significado; CSS define presentacion y JavaScript agrega comportamiento.",
  },
  {
    subjectId: "web",
    unit: 1,
    difficulty: "facil",
    question: "Que tecnologia se utiliza principalmente para aplicar estilos visuales a una pagina web?",
    options: ["CSS", "SQL", "Git", "JSON"],
    answer: 0,
    explanation: "CSS describe colores, espaciado, tipografia, layout y reglas visuales del documento HTML.",
  },
  {
    subjectId: "web",
    unit: 1,
    difficulty: "intermedio",
    question: "Por que es recomendable separar HTML, CSS y JavaScript en una aplicacion web?",
    options: [
      "Porque mejora mantenibilidad al separar estructura, presentacion y comportamiento.",
      "Porque impide que el navegador use memoria cache.",
      "Porque elimina la necesidad de pruebas unitarias.",
      "Porque obliga a usar una arquitectura de microservicios.",
    ],
    answer: 0,
    explanation: "La separacion de responsabilidades reduce acoplamiento y facilita cambios independientes.",
  },
  {
    subjectId: "web",
    unit: 2,
    difficulty: "intermedio",
    question: "En el patron MVC, que responsabilidad corresponde al controlador?",
    options: [
      "Recibir la peticion, coordinar el modelo y seleccionar la respuesta adecuada.",
      "Definir exclusivamente los estilos visuales de la interfaz.",
      "Almacenar los archivos estaticos en el repositorio Git.",
      "Reemplazar por completo la capa de persistencia ORM.",
    ],
    answer: 0,
    explanation: "El controlador actua como intermediario entre la solicitud, la logica de dominio y la vista o respuesta.",
  },
  {
    subjectId: "web",
    unit: 2,
    difficulty: "facil",
    question: "Cual es una caracteristica esperada de una API REST?",
    options: [
      "Usar recursos identificables y metodos HTTP como GET, POST, PUT o DELETE.",
      "Depender siempre de una interfaz grafica instalada en el servidor.",
      "Ejecutar todo el codigo en el navegador sin comunicacion de red.",
      "Evitar el uso de codigos de estado HTTP.",
    ],
    answer: 0,
    explanation: "REST organiza la comunicacion alrededor de recursos y operaciones HTTP bien definidas.",
  },
  {
    subjectId: "web",
    unit: 2,
    difficulty: "dificil",
    question: "Si una aplicacion usa ORM, cual es el beneficio tecnico mas directo?",
    options: [
      "Mapear entidades del dominio a tablas, reduciendo codigo repetitivo de persistencia.",
      "Eliminar la necesidad de disenar un modelo de datos coherente.",
      "Convertir automaticamente una aplicacion monolitica en serverless.",
      "Garantizar que todas las consultas sean siempre mas rapidas que SQL manual.",
    ],
    answer: 0,
    explanation: "Un ORM facilita el mapeo objeto-relacional, aunque no reemplaza el diseno ni el analisis de rendimiento.",
  },
  {
    subjectId: "web",
    unit: 2,
    difficulty: "dificil",
    question: "Que evalua principalmente una prueba unitaria en el backend?",
    options: [
      "Una unidad pequena de logica aislada, verificando entradas, salidas y casos limite.",
      "La aceptacion institucional del sistema por parte de todos los usuarios.",
      "El rendimiento de toda la infraestructura en produccion.",
      "La compatibilidad fisica de sensores y actuadores.",
    ],
    answer: 0,
    explanation: "Las pruebas unitarias buscan comprobar componentes pequenos de manera aislada y repetible.",
  },
  {
    subjectId: "web",
    unit: 3,
    difficulty: "intermedio",
    question: "Que diferencia conceptual existe entre SOA y microservicios?",
    options: [
      "Microservicios tiende a servicios pequenos, autonomos y desplegables independientemente.",
      "SOA solo se ejecuta en navegadores y microservicios solo en bases de datos.",
      "Microservicios prohibe el uso de APIs y mensajeria.",
      "SOA no permite reutilizar servicios entre sistemas.",
    ],
    answer: 0,
    explanation: "Ambos se orientan a servicios, pero microservicios enfatiza autonomia, despliegue independiente y limites pequenos.",
  },
  {
    subjectId: "web",
    unit: 3,
    difficulty: "dificil",
    question: "En una arquitectura de microservicios, que riesgo aparece si varios servicios comparten directamente la misma base de datos?",
    options: [
      "Se incrementa el acoplamiento y se dificulta la evolucion independiente de cada servicio.",
      "Se garantiza automaticamente consistencia eventual sin diseno adicional.",
      "Se elimina la necesidad de contratos entre servicios.",
      "Se evita cualquier problema de disponibilidad.",
    ],
    answer: 0,
    explanation: "Compartir persistencia interna rompe limites de servicio y crea dependencias fuertes.",
  },
  {
    subjectId: "web",
    unit: 4,
    difficulty: "facil",
    question: "Para que sirve un sistema de control de versiones como Git?",
    options: [
      "Registrar cambios, colaborar y recuperar versiones del codigo fuente.",
      "Disenar el modelo entidad-relacion automaticamente.",
      "Crear sensores fisicos conectados por GPIO.",
      "Sustituir las pruebas funcionales del sistema.",
    ],
    answer: 0,
    explanation: "Git permite trazabilidad, trabajo colaborativo y gestion de ramas en proyectos de software.",
  },
  {
    subjectId: "web",
    unit: 4,
    difficulty: "intermedio",
    question: "Cual es el objetivo central de DevOps en proyectos web?",
    options: [
      "Integrar desarrollo y operaciones para entregar software de forma continua y confiable.",
      "Separar por completo a quienes programan de quienes despliegan.",
      "Evitar automatizar pruebas para reducir tiempos iniciales.",
      "Reemplazar el diseno de arquitectura por documentacion manual.",
    ],
    answer: 0,
    explanation: "DevOps promueve colaboracion, automatizacion, integracion continua, despliegue y monitoreo.",
  },
  {
    subjectId: "web",
    unit: 4,
    difficulty: "dificil",
    question: "Que problema busca reducir una tuberia CI/CD bien disenada?",
    options: [
      "Errores manuales al integrar, probar y desplegar cambios frecuentes.",
      "La necesidad de escribir codigo fuente.",
      "La existencia de requerimientos funcionales.",
      "La latencia fisica de una red inalambrica.",
    ],
    answer: 0,
    explanation: "CI/CD automatiza pasos repetibles para detectar fallos temprano y desplegar con mayor control.",
  },
];

const redesQuestions = [
  {
    subjectId: "redes",
    unit: 1,
    difficulty: "facil",
    question: "Que caracteriza a una red inalambrica frente a una red cableada tradicional?",
    options: [
      "La transmision usa un medio radioelectrico en lugar de un conductor fisico dedicado.",
      "Siempre tiene menor latencia que una red de fibra optica.",
      "No requiere protocolos de acceso al medio.",
      "No necesita mecanismos de seguridad.",
    ],
    answer: 0,
    explanation: "Las redes inalambricas comparten espectro y requieren control de interferencia, acceso y seguridad.",
  },
  {
    subjectId: "redes",
    unit: 1,
    difficulty: "intermedio",
    question: "Por que la interferencia es un factor critico en redes inalambricas?",
    options: [
      "Porque varios dispositivos pueden competir por el mismo espectro y degradar la senal.",
      "Porque convierte automaticamente la red en una topologia de anillo.",
      "Porque elimina la necesidad de autenticacion.",
      "Porque impide usar direccionamiento IP.",
    ],
    answer: 0,
    explanation: "El medio compartido hace que la calidad de senal y la planificacion de canales sean esenciales.",
  },
  {
    subjectId: "redes",
    unit: 2,
    difficulty: "facil",
    question: "Que objetivo general persigue la evolucion de redes moviles desde generaciones anteriores hacia 4G y 5G?",
    options: [
      "Aumentar capacidad, velocidad, eficiencia espectral y soporte de nuevos servicios.",
      "Eliminar por completo la necesidad de estaciones base.",
      "Usar solamente conmutacion de circuitos.",
      "Desactivar el trafico de datos para priorizar voz analogica.",
    ],
    answer: 0,
    explanation: "Las generaciones moviles evolucionan para soportar mas usuarios, datos y servicios con mejor desempeno.",
  },
  {
    subjectId: "redes",
    unit: 2,
    difficulty: "intermedio",
    question: "Cual es el proposito de MPLS en una red de transporte?",
    options: [
      "Conmutar paquetes mediante etiquetas para dirigir trafico de forma eficiente.",
      "Sustituir toda direccion IP por direcciones MAC publicas.",
      "Crear exclusivamente redes inalambricas domesticas.",
      "Ejecutar aplicaciones serverless en el cliente.",
    ],
    answer: 0,
    explanation: "MPLS usa etiquetas para decisiones de reenvio y permite ingenieria de trafico.",
  },
  {
    subjectId: "redes",
    unit: 2,
    difficulty: "dificil",
    question: "Que ventaja aporta SDN al separar el plano de control del plano de datos?",
    options: [
      "Permite programar politicas de red desde un controlador centralizado.",
      "Obliga a configurar cada switch solo por consola fisica.",
      "Impide la automatizacion de rutas y reglas.",
      "Elimina cualquier necesidad de monitoreo.",
    ],
    answer: 0,
    explanation: "SDN facilita control central, automatizacion y cambios dinamicos sobre dispositivos de red.",
  },
  {
    subjectId: "redes",
    unit: 2,
    difficulty: "dificil",
    question: "Que busca NFV en la arquitectura de redes moderna?",
    options: [
      "Virtualizar funciones de red para ejecutarlas sobre infraestructura general.",
      "Reemplazar TCP/IP por senales analogicas.",
      "Eliminar firewalls, balanceadores y routers logicos.",
      "Convertir cada usuario en proveedor de espectro.",
    ],
    answer: 0,
    explanation: "NFV desacopla funciones de red del hardware dedicado, aumentando flexibilidad y escalabilidad.",
  },
  {
    subjectId: "redes",
    unit: 3,
    difficulty: "facil",
    question: "Que tipo de protocolo es OSPF?",
    options: [
      "Un protocolo de enrutamiento de estado de enlace usado dentro de un sistema autonomo.",
      "Un protocolo de presentacion para hojas de estilo web.",
      "Un sistema de archivos distribuido.",
      "Un mecanismo para tokenizar texto.",
    ],
    answer: 0,
    explanation: "OSPF calcula rutas internas usando informacion de estado de enlace.",
  },
  {
    subjectId: "redes",
    unit: 3,
    difficulty: "intermedio",
    question: "Para que se utiliza STP en redes Ethernet con switches?",
    options: [
      "Evitar bucles de capa 2 mediante una topologia logica libre de ciclos.",
      "Asignar etiquetas MPLS en redes WAN.",
      "Entrenar modelos predictivos de clasificacion.",
      "Desplegar contenedores de microservicios.",
    ],
    answer: 0,
    explanation: "STP bloquea enlaces redundantes cuando es necesario para prevenir tormentas por bucles.",
  },
  {
    subjectId: "redes",
    unit: 3,
    difficulty: "dificil",
    question: "Por que BGP es fundamental para Internet?",
    options: [
      "Porque intercambia rutas entre sistemas autonomos y aplica politicas de enrutamiento.",
      "Porque define los estilos de una pagina HTML.",
      "Porque reemplaza el direccionamiento IP privado en una LAN.",
      "Porque evita toda negociacion entre proveedores.",
    ],
    answer: 0,
    explanation: "BGP es el protocolo exterior que permite el enrutamiento interdominio en Internet.",
  },
  {
    subjectId: "redes",
    unit: 4,
    difficulty: "facil",
    question: "Que significa QoS en redes?",
    options: [
      "Calidad de servicio aplicada para gestionar prioridades, retardo, perdida y ancho de banda.",
      "Un lenguaje de programacion para microcontroladores.",
      "Un modelo de mineria descriptiva.",
      "Un repositorio de codigo distribuido.",
    ],
    answer: 0,
    explanation: "QoS agrupa mecanismos para tratar trafico con distintos niveles de prioridad.",
  },
  {
    subjectId: "redes",
    unit: 4,
    difficulty: "intermedio",
    question: "Que trafico suele requerir mayor prioridad en una politica QoS?",
    options: [
      "Voz y video en tiempo real, por su sensibilidad a latencia y jitter.",
      "Descargas diferidas sin limite de tiempo.",
      "Copias de seguridad programadas en horario nocturno.",
      "Actualizaciones que no afectan servicios interactivos.",
    ],
    answer: 0,
    explanation: "Las aplicaciones en tiempo real toleran poco retardo, variacion de retardo y perdida.",
  },
  {
    subjectId: "redes",
    unit: 4,
    difficulty: "dificil",
    question: "En una red congestionada, que efecto busca una clasificacion QoS correcta?",
    options: [
      "Aplicar colas y prioridades para preservar el desempeno de servicios criticos.",
      "Aumentar fisicamente el ancho de banda sin cambiar infraestructura.",
      "Eliminar todos los paquetes de baja prioridad siempre.",
      "Convertir protocolos de enrutamiento internos en externos.",
    ],
    answer: 0,
    explanation: "QoS no crea capacidad por si sola; administra recursos para cumplir objetivos de servicio.",
  },
];

const softwareQuestions = [
  {
    subjectId: "software",
    unit: 1,
    difficulty: "facil",
    question: "Cual es el proposito principal de la ingenieria de software?",
    options: [
      "Aplicar metodos sistematicos para desarrollar, operar y mantener software de calidad.",
      "Escribir codigo sin documentacion ni verificacion.",
      "Sustituir la comunicacion con usuarios por suposiciones tecnicas.",
      "Limitar el software a programas pequenos sin mantenimiento.",
    ],
    answer: 0,
    explanation: "La disciplina busca procesos, calidad, gestion y mantenimiento durante todo el ciclo de vida.",
  },
  {
    subjectId: "software",
    unit: 1,
    difficulty: "intermedio",
    question: "Que problema suele aparecer cuando se inicia un proyecto sin proceso de ingenieria de software?",
    options: [
      "Requerimientos ambiguos, estimaciones debiles y mayor riesgo de retrabajo.",
      "Mayor trazabilidad automatica de decisiones.",
      "Reduccion garantizada del costo de mantenimiento.",
      "Eliminacion de defectos en produccion.",
    ],
    answer: 0,
    explanation: "La ausencia de proceso incrementa incertidumbre y errores acumulados.",
  },
  {
    subjectId: "software",
    unit: 2,
    difficulty: "facil",
    question: "Que describe un requerimiento funcional?",
    options: [
      "Una funcion o comportamiento que el sistema debe realizar.",
      "Unicamente el color de la interfaz.",
      "La marca del equipo donde se despliega el sistema.",
      "La cantidad de carpetas del repositorio.",
    ],
    answer: 0,
    explanation: "Los requerimientos funcionales expresan servicios, acciones o respuestas esperadas del sistema.",
  },
  {
    subjectId: "software",
    unit: 2,
    difficulty: "intermedio",
    question: "Por que es importante definir el alcance del producto en un documento de requerimientos?",
    options: [
      "Porque delimita que incluye y que queda fuera del sistema a construir.",
      "Porque reemplaza la validacion con usuarios finales.",
      "Porque elimina la necesidad de restricciones tecnicas.",
      "Porque permite codificar sin modelo de datos.",
    ],
    answer: 0,
    explanation: "El alcance evita expectativas contradictorias y ayuda a controlar cambios.",
  },
  {
    subjectId: "software",
    unit: 2,
    difficulty: "dificil",
    question: "Que consecuencia tiene un requerimiento no verificable?",
    options: [
      "Dificulta comprobar objetivamente si el sistema cumple lo solicitado.",
      "Aumenta automaticamente la cobertura de pruebas.",
      "Convierte el requerimiento en una historia de usuario completa.",
      "Hace innecesaria la negociacion con el cliente.",
    ],
    answer: 0,
    explanation: "Los requerimientos deben poder evaluarse mediante criterios, pruebas o evidencias claras.",
  },
  {
    subjectId: "software",
    unit: 3,
    difficulty: "facil",
    question: "Que representa un caso de uso?",
    options: [
      "Una interaccion entre actor y sistema para alcanzar un objetivo observable.",
      "Una tabla fisica obligatoria en toda base de datos.",
      "Una regla CSS para componentes visuales.",
      "Una metrica de clusterizacion.",
    ],
    answer: 0,
    explanation: "Los casos de uso describen objetivos del usuario y respuestas del sistema.",
  },
  {
    subjectId: "software",
    unit: 3,
    difficulty: "intermedio",
    question: "Que aporta el modelado de requerimientos al analisis?",
    options: [
      "Organiza informacion del dominio, actores, restricciones y comportamiento esperado.",
      "Elimina la necesidad de entrevistas o levantamiento de informacion.",
      "Garantiza que no existiran cambios durante el proyecto.",
      "Sustituye el diseno arquitectonico de bajo nivel.",
    ],
    answer: 0,
    explanation: "Modelar permite comprender, comunicar y validar lo que el sistema debe resolver.",
  },
  {
    subjectId: "software",
    unit: 4,
    difficulty: "facil",
    question: "Que caracteriza a una metodologia agil?",
    options: [
      "Trabajo iterativo, colaboracion con el cliente y adaptacion al cambio.",
      "Planificacion fija que no acepta retroalimentacion.",
      "Entrega unica solo al final del proyecto.",
      "Ausencia total de pruebas y revision.",
    ],
    answer: 0,
    explanation: "Los enfoques agiles priorizan ciclos cortos, feedback y valor incremental.",
  },
  {
    subjectId: "software",
    unit: 4,
    difficulty: "intermedio",
    question: "En Scrum, cual es el sentido de un sprint?",
    options: [
      "Un ciclo corto y limitado en tiempo para producir un incremento revisable.",
      "Una fase indefinida sin objetivos medibles.",
      "Un documento que reemplaza al backlog.",
      "Una tecnica exclusiva de redes inalambricas.",
    ],
    answer: 0,
    explanation: "El sprint permite inspeccionar avances y adaptar el trabajo periodicamente.",
  },
  {
    subjectId: "software",
    unit: 4,
    difficulty: "dificil",
    question: "Que riesgo aparece si una historia de usuario no tiene criterios de aceptacion?",
    options: [
      "El equipo puede interpretar de forma distinta cuando la historia esta terminada.",
      "La historia se vuelve automaticamente mas pequena.",
      "El producto queda protegido contra cambios.",
      "La estimacion deja de ser necesaria.",
    ],
    answer: 0,
    explanation: "Los criterios de aceptacion definen condiciones observables para validar la entrega.",
  },
  {
    subjectId: "software",
    unit: 5,
    difficulty: "intermedio",
    question: "Que busca el diseno arquitectonico de software?",
    options: [
      "Definir componentes, responsabilidades, relaciones y decisiones estructurales clave.",
      "Seleccionar solo los colores finales de la pantalla.",
      "Documentar exclusivamente los nombres de los programadores.",
      "Evitar cualquier evaluacion de calidad.",
    ],
    answer: 0,
    explanation: "La arquitectura organiza la solucion y condiciona atributos como mantenibilidad, seguridad y escalabilidad.",
  },
  {
    subjectId: "software",
    unit: 5,
    difficulty: "dificil",
    question: "Por que el bajo acoplamiento y la alta cohesion son objetivos deseables en diseno?",
    options: [
      "Porque facilitan mantenimiento, pruebas y evolucion independiente de los componentes.",
      "Porque obligan a duplicar toda la logica del sistema.",
      "Porque impiden dividir responsabilidades.",
      "Porque eliminan la necesidad de interfaces.",
    ],
    answer: 0,
    explanation: "Componentes cohesivos y poco acoplados son mas comprensibles, cambiables y testeables.",
  },
];

const mineriaQuestions = [
  {
    subjectId: "mineria",
    unit: 1,
    difficulty: "facil",
    question: "Que significa KDD en el contexto de mineria de datos?",
    options: [
      "Proceso de descubrimiento de conocimiento en bases de datos.",
      "Un protocolo de enrutamiento exterior.",
      "Un patron de diseno para aplicaciones web.",
      "Un controlador de interrupciones embebidas.",
    ],
    answer: 0,
    explanation: "KDD comprende seleccion, limpieza, transformacion, mineria e interpretacion de resultados.",
  },
  {
    subjectId: "mineria",
    unit: 1,
    difficulty: "intermedio",
    question: "Por que la limpieza de datos es una etapa critica antes de entrenar modelos?",
    options: [
      "Porque valores faltantes, duplicados o inconsistentes pueden distorsionar los patrones aprendidos.",
      "Porque elimina la necesidad de entender el problema de negocio.",
      "Porque convierte cualquier algoritmo en no supervisado.",
      "Porque garantiza exactitud perfecta en todos los modelos.",
    ],
    answer: 0,
    explanation: "La calidad del modelo depende en gran medida de la calidad y preparacion de los datos.",
  },
  {
    subjectId: "mineria",
    unit: 1,
    difficulty: "dificil",
    question: "Que objetivo tiene la reduccion de dimensionalidad?",
    options: [
      "Disminuir variables conservando informacion relevante para simplificar analisis o modelos.",
      "Aumentar ruido para evitar sobreajuste.",
      "Eliminar la variable objetivo de un modelo supervisado.",
      "Convertir datos numericos en protocolos de red.",
    ],
    answer: 0,
    explanation: "Reducir dimensiones puede mejorar interpretabilidad, costo computacional y desempeno.",
  },
  {
    subjectId: "mineria",
    unit: 2,
    difficulty: "facil",
    question: "Que caracteriza a un modelo predictivo supervisado?",
    options: [
      "Aprende a partir de ejemplos con una variable objetivo conocida.",
      "No utiliza datos historicos.",
      "Solo agrupa observaciones sin etiquetas.",
      "No requiere evaluacion de resultados.",
    ],
    answer: 0,
    explanation: "Clasificacion y regresion son tecnicas supervisadas porque usan respuestas conocidas durante el entrenamiento.",
  },
  {
    subjectId: "mineria",
    unit: 2,
    difficulty: "intermedio",
    question: "Cuando se aplica un algoritmo de clasificacion?",
    options: [
      "Cuando la variable objetivo pertenece a categorias discretas.",
      "Cuando se desea predecir un valor continuo exclusivamente.",
      "Cuando no existe variable objetivo.",
      "Cuando solo se quiere medir la latencia de red.",
    ],
    answer: 0,
    explanation: "Clasificar significa asignar una clase, como aprobado/reprobado, fraude/no fraude o positivo/negativo.",
  },
  {
    subjectId: "mineria",
    unit: 2,
    difficulty: "dificil",
    question: "Que indica una matriz de confusion en un problema de clasificacion?",
    options: [
      "La distribucion de predicciones correctas e incorrectas por clase real y predicha.",
      "El numero de routers de una red.",
      "El flujo de pantallas de una aplicacion web.",
      "La estructura fisica de un microcontrolador.",
    ],
    answer: 0,
    explanation: "De la matriz de confusion se derivan metricas como exactitud, sensibilidad y especificidad.",
  },
  {
    subjectId: "mineria",
    unit: 2,
    difficulty: "dificil",
    question: "Que problema describe el sobreajuste en un arbol de decision?",
    options: [
      "El modelo aprende demasiado el ruido del entrenamiento y generaliza mal.",
      "El modelo ignora por completo todas las variables predictoras.",
      "El algoritmo deja de ser supervisado.",
      "La matriz de confusion desaparece.",
    ],
    answer: 0,
    explanation: "La poda y la validacion ayudan a controlar modelos demasiado complejos.",
  },
  {
    subjectId: "mineria",
    unit: 3,
    difficulty: "facil",
    question: "Que tecnica busca descubrir grupos naturales en datos sin etiquetas?",
    options: ["Clustering", "Regresion lineal", "Pruebas unitarias", "Control de versiones"],
    answer: 0,
    explanation: "El clustering es aprendizaje no supervisado orientado a agrupar observaciones similares.",
  },
  {
    subjectId: "mineria",
    unit: 3,
    difficulty: "intermedio",
    question: "Que tipo de patrones identifica el algoritmo Apriori?",
    options: [
      "Reglas de asociacion entre elementos que aparecen juntos con frecuencia.",
      "Rutas BGP entre sistemas autonomos.",
      "Interrupciones de hardware embebido.",
      "Estilos visuales para HTML.",
    ],
    answer: 0,
    explanation: "Apriori se usa en analisis de canasta y descubrimiento de itemsets frecuentes.",
  },
  {
    subjectId: "mineria",
    unit: 3,
    difficulty: "dificil",
    question: "Que evalua la separacion en un modelo de agrupamiento?",
    options: [
      "Que tan alejados estan los clusters entre si.",
      "Que tan pequeno es el archivo fuente.",
      "Cuantos endpoints REST existen.",
      "Cuantos paquetes descarta QoS.",
    ],
    answer: 0,
    explanation: "Un buen clustering suele buscar alta homogeneidad interna y buena separacion externa.",
  },
  {
    subjectId: "mineria",
    unit: 4,
    difficulty: "intermedio",
    question: "Que paso es esencial antes de analizar frecuencias de palabras en mineria de texto?",
    options: [
      "Limpiar y tokenizar el texto, gestionando signos, stop words y normalizacion.",
      "Configurar OSPF multi-area.",
      "Definir pines GPIO.",
      "Crear ramas Git para cada palabra.",
    ],
    answer: 0,
    explanation: "La preparacion textual permite contar unidades significativas y reducir ruido.",
  },
  {
    subjectId: "mineria",
    unit: 4,
    difficulty: "dificil",
    question: "Que diferencia general existe entre datos vectoriales y raster en analisis geoespacial?",
    options: [
      "Vectorial representa puntos, lineas o poligonos; raster representa celdas o pixeles.",
      "Raster solo se usa para texto y vectorial solo para audio.",
      "Vectorial no puede contener coordenadas.",
      "Raster es un protocolo de enrutamiento.",
    ],
    answer: 0,
    explanation: "Ambos modelos representan espacio, pero con estructuras de datos diferentes.",
  },
];

const embebidosQuestions = [
  {
    subjectId: "embebidos",
    unit: 1,
    difficulty: "facil",
    question: "Que es un sistema embebido?",
    options: [
      "Un sistema computacional dedicado a cumplir funciones especificas dentro de un producto mayor.",
      "Una pagina web que solo usa HTML.",
      "Un protocolo de enrutamiento entre proveedores.",
      "Un modelo estadistico sin datos de entrada.",
    ],
    answer: 0,
    explanation: "Los sistemas embebidos integran hardware y software para una tarea definida.",
  },
  {
    subjectId: "embebidos",
    unit: 1,
    difficulty: "intermedio",
    question: "Que condicion suele ser prioritaria en el diseno de sistemas embebidos?",
    options: [
      "Restricciones de tiempo, memoria, energia, costo y confiabilidad.",
      "Uso ilimitado de recursos de nube publica.",
      "Ausencia total de interaccion con hardware.",
      "Dependencia exclusiva de navegadores web.",
    ],
    answer: 0,
    explanation: "El diseno embebido debe considerar recursos limitados y comportamiento predecible.",
  },
  {
    subjectId: "embebidos",
    unit: 1,
    difficulty: "dificil",
    question: "Que implica el diseno basado en plataforma?",
    options: [
      "Reutilizar una base de hardware/software conocida para acelerar y controlar el desarrollo.",
      "Crear cada componente desde cero sin reutilizacion.",
      "Desarrollar solo interfaces graficas de escritorio.",
      "Eliminar la validacion del sistema fisico.",
    ],
    answer: 0,
    explanation: "Una plataforma reduce complejidad al proveer componentes y patrones ya establecidos.",
  },
  {
    subjectId: "embebidos",
    unit: 2,
    difficulty: "facil",
    question: "Que funcion cumple un microcontrolador en un sistema embebido?",
    options: [
      "Ejecutar instrucciones y controlar perifericos integrados para una tarea especifica.",
      "Administrar rutas BGP entre operadores.",
      "Aplicar estilos CSS al navegador.",
      "Crear reglas de asociacion con Apriori.",
    ],
    answer: 0,
    explanation: "El microcontrolador integra CPU, memoria y perifericos para control directo de dispositivos.",
  },
  {
    subjectId: "embebidos",
    unit: 2,
    difficulty: "intermedio",
    question: "Para que se usan comunmente las interfaces GPIO?",
    options: [
      "Leer o escribir senales digitales de proposito general.",
      "Entrenar modelos de regresion.",
      "Definir rutas entre sistemas autonomos.",
      "Versionar archivos de codigo fuente.",
    ],
    answer: 0,
    explanation: "GPIO permite conectar botones, LEDs, sensores simples y actuadores digitales.",
  },
  {
    subjectId: "embebidos",
    unit: 2,
    difficulty: "dificil",
    question: "Que permite un lenguaje de descripcion de hardware como VHDL o Verilog?",
    options: [
      "Modelar estructura y comportamiento de circuitos digitales para simulacion o sintesis.",
      "Escribir documentos SRS automaticamente.",
      "Clasificar tweets positivos y negativos.",
      "Crear endpoints REST sin servidor.",
    ],
    answer: 0,
    explanation: "Los HDL describen hardware, no solo programas secuenciales tradicionales.",
  },
  {
    subjectId: "embebidos",
    unit: 3,
    difficulty: "facil",
    question: "Que es software embebido?",
    options: [
      "Codigo que controla funciones especificas de un dispositivo integrado con hardware.",
      "Unicamente una aplicacion de oficina.",
      "Un documento de requerimientos sin ejecucion.",
      "Una tabla de rutas de Internet.",
    ],
    answer: 0,
    explanation: "El software embebido interactua estrechamente con perifericos, sensores y restricciones del dispositivo.",
  },
  {
    subjectId: "embebidos",
    unit: 3,
    difficulty: "intermedio",
    question: "Para que sirve una interrupcion en un sistema embebido?",
    options: [
      "Atender eventos de hardware o temporizadores sin esperar continuamente en el programa principal.",
      "Ordenar datos con una expresion regular.",
      "Aplicar QoS a paquetes de voz.",
      "Crear componentes visuales en React.",
    ],
    answer: 0,
    explanation: "Las interrupciones permiten respuesta eficiente ante eventos asincronos.",
  },
  {
    subjectId: "embebidos",
    unit: 3,
    difficulty: "dificil",
    question: "Por que la depuracion de software embebido puede ser mas compleja que en una aplicacion convencional?",
    options: [
      "Porque depende de tiempo real, perifericos, hardware fisico y recursos limitados.",
      "Porque siempre se ejecuta en navegadores con memoria ilimitada.",
      "Porque no existen herramientas de simulacion.",
      "Porque no interactua con entradas externas.",
    ],
    answer: 0,
    explanation: "El entorno fisico y las restricciones temporales hacen mas dificil reproducir y observar fallos.",
  },
  {
    subjectId: "embebidos",
    unit: 4,
    difficulty: "facil",
    question: "Que tecnologias de comunicacion aparecen comunmente en sistemas embebidos modernos?",
    options: ["USB, WiFi, Bluetooth y redes celulares.", "HTML, CSS y ORM.", "BGP, IS-IS y Scrum.", "KDD, Apriori y SRS."],
    answer: 0,
    explanation: "Los sistemas embebidos pueden conectarse por buses cableados o tecnologias inalambricas.",
  },
  {
    subjectId: "embebidos",
    unit: 4,
    difficulty: "intermedio",
    question: "Por que se usan tecnologias inalambricas de bajo consumo en aplicaciones IoT?",
    options: [
      "Porque prolongan la autonomia energetica de dispositivos alimentados por bateria.",
      "Porque requieren siempre mayor ancho de banda que fibra optica.",
      "Porque eliminan toda necesidad de protocolos.",
      "Porque solo funcionan en servidores web.",
    ],
    answer: 0,
    explanation: "En IoT muchas aplicaciones priorizan bajo consumo y alcance suficiente sobre maxima velocidad.",
  },
  {
    subjectId: "embebidos",
    unit: 4,
    difficulty: "dificil",
    question: "Al elegir comunicacion para monitoreo remoto embebido, que criterio tecnico es mas relevante?",
    options: [
      "Balancear alcance, consumo energetico, tasa de datos, costo y disponibilidad de red.",
      "Escoger siempre la tecnologia con mayor velocidad teorica.",
      "Ignorar el ambiente fisico de instalacion.",
      "Usar solo comunicacion cableada aunque el dispositivo sea movil.",
    ],
    answer: 0,
    explanation: "La tecnologia adecuada depende del caso de uso y sus restricciones operativas.",
  },
];

export const difficultyLabels = {
  facil: "Facil",
  intermedio: "Intermedio",
  dificil: "Dificil",
};

const conceptMap = {
  web: {
    facil: [
      ["HTML semantico", "organizar el contenido de una pagina con etiquetas significativas"],
      ["CSS", "controlar la presentacion visual de documentos web"],
      ["JavaScript", "agregar comportamiento dinamico en el navegador"],
      ["DOM", "representar el documento para que pueda ser consultado o modificado"],
      ["cliente-servidor", "separar solicitudes del cliente y respuestas del servidor"],
      ["API REST", "exponer recursos mediante operaciones HTTP"],
      ["MVC", "separar modelo, vista y controlador"],
      ["Git", "registrar cambios y colaborar en el codigo"],
      ["DevOps", "integrar desarrollo, despliegue y operacion"],
      ["serverless", "ejecutar funciones sin administrar servidores directamente"],
    ],
    intermedio: [
      ["separacion de responsabilidades", "reducir acoplamiento entre estructura, estilo y logica"],
      ["validacion del lado cliente", "mejorar experiencia sin reemplazar la validacion del servidor"],
      ["controlador MVC", "coordinar solicitudes y reglas de aplicacion"],
      ["ORM", "mapear entidades a persistencia relacional"],
      ["pruebas unitarias", "verificar unidades pequenas de logica de forma repetible"],
      ["SOA", "organizar capacidades como servicios reutilizables"],
      ["microservicios", "desplegar servicios pequenos e independientes"],
      ["estado de aplicacion", "mantener coherencia entre interfaz y datos"],
      ["ramas Git", "aislar cambios antes de integrarlos"],
      ["integracion continua", "validar cambios automaticamente antes del despliegue"],
    ],
    dificil: [
      ["contratos REST", "evitar rupturas entre clientes y servicios"],
      ["consistencia en microservicios", "coordinar datos distribuidos sin acoplar bases internas"],
      ["serverless computing", "balancear escalado automatico con limites de ejecucion"],
      ["cobertura de pruebas", "detectar regresiones en componentes criticos"],
      ["despliegue continuo", "automatizar entregas con controles de calidad"],
      ["observabilidad", "analizar fallos mediante metricas, logs y trazas"],
      ["idempotencia", "permitir reintentos seguros de operaciones distribuidas"],
      ["versionamiento semantico", "comunicar compatibilidad entre releases"],
      ["seguridad de API", "proteger recursos mediante autenticacion y autorizacion"],
      ["persistencia por servicio", "preservar autonomia en arquitecturas de microservicios"],
    ],
  },
  redes: {
    facil: [
      ["red inalambrica", "transmitir datos usando ondas de radio"],
      ["punto de acceso", "conectar clientes inalambricos a la red"],
      ["red movil", "ofrecer comunicacion a usuarios en movimiento"],
      ["MPLS", "reenviar paquetes mediante etiquetas"],
      ["SDN", "programar la red desde un plano de control"],
      ["NFV", "virtualizar funciones de red"],
      ["OSPF", "calcular rutas internas por estado de enlace"],
      ["STP", "prevenir bucles en capa 2"],
      ["BGP", "intercambiar rutas entre sistemas autonomos"],
      ["QoS", "priorizar trafico segun necesidades del servicio"],
    ],
    intermedio: [
      ["interferencia", "afectar calidad de senal y rendimiento inalambrico"],
      ["eficiencia espectral", "transportar mas informacion en el espectro disponible"],
      ["ingenieria de trafico", "dirigir flujos para optimizar recursos"],
      ["controlador SDN", "centralizar decisiones de politica de red"],
      ["funciones virtualizadas", "desacoplar servicios del hardware dedicado"],
      ["OSPF multi-area", "escalar el enrutamiento interno con areas"],
      ["convergencia", "actualizar rutas despues de un cambio topologico"],
      ["eleccion STP", "determinar puertos activos y bloqueados"],
      ["politicas BGP", "controlar preferencia y propagacion de rutas"],
      ["jitter", "medir variacion del retardo en trafico en tiempo real"],
    ],
    dificil: [
      ["redistribucion de rutas", "intercambiar informacion entre protocolos con control"],
      ["atributos BGP", "influir en seleccion de rutas interdominio"],
      ["QoS extremo a extremo", "mantener prioridades entre multiples dominios de red"],
      ["virtualizacion de red", "escalar servicios sin depender de appliances fisicos"],
      ["resiliencia", "mantener conectividad ante fallos de enlaces o nodos"],
      ["latencia", "limitar retardo en aplicaciones sensibles al tiempo"],
      ["planificacion de canales", "reducir interferencia en despliegues inalambricos"],
      ["segmentacion", "aislar trafico para seguridad y administracion"],
      ["control distribuido", "evitar puntos unicos de falla en arquitecturas programables"],
      ["colas QoS", "administrar congestion segun prioridad de trafico"],
    ],
  },
  software: {
    facil: [
      ["ingenieria de software", "desarrollar software con metodos sistematicos"],
      ["requerimiento funcional", "describir una conducta observable del sistema"],
      ["requerimiento no funcional", "definir atributos de calidad o restricciones"],
      ["actor", "representar un rol que interactua con el sistema"],
      ["caso de uso", "describir una meta alcanzada mediante interaccion"],
      ["SRS", "documentar requerimientos de forma organizada"],
      ["Scrum", "gestionar trabajo iterativo e incremental"],
      ["historia de usuario", "expresar una necesidad desde la perspectiva del usuario"],
      ["diseno arquitectonico", "organizar componentes y relaciones principales"],
      ["cohesion", "concentrar responsabilidades relacionadas en un componente"],
    ],
    intermedio: [
      ["alcance del producto", "delimitar inclusiones y exclusiones del sistema"],
      ["trazabilidad", "relacionar requerimientos, diseno, codigo y pruebas"],
      ["criterios de aceptacion", "definir condiciones para validar una historia"],
      ["backlog", "priorizar el trabajo pendiente del producto"],
      ["sprint", "producir un incremento en un ciclo fijo"],
      ["modelado de requerimientos", "comprender dominio, procesos y restricciones"],
      ["prototipo", "validar ideas con usuarios antes de construir todo"],
      ["acoplamiento", "medir dependencia entre modulos"],
      ["patrones de diseno", "reutilizar soluciones probadas a problemas frecuentes"],
      ["mantenibilidad", "facilitar correcciones y evolucion del software"],
    ],
    dificil: [
      ["ambiguedad de requerimientos", "provocar interpretaciones contradictorias del alcance"],
      ["deuda tecnica", "acumular decisiones que encarecen cambios futuros"],
      ["arquitectura evolutiva", "permitir cambios sin degradar la estructura"],
      ["validacion", "confirmar que el producto satisface necesidades reales"],
      ["verificacion", "comprobar que el producto cumple especificaciones"],
      ["trade-off arquitectonico", "equilibrar atributos de calidad en conflicto"],
      ["refactorizacion", "mejorar estructura interna sin cambiar comportamiento externo"],
      ["gestion de cambios", "controlar impacto sobre alcance, costo y cronograma"],
      ["diseno modular", "dividir responsabilidades para probar y mantener mejor"],
      ["calidad de software", "evaluar atributos como confiabilidad, usabilidad y seguridad"],
    ],
  },
  mineria: {
    facil: [
      ["KDD", "descubrir conocimiento a partir de datos"],
      ["seleccion de datos", "escoger fuentes y variables relevantes"],
      ["limpieza de datos", "corregir valores faltantes, duplicados o inconsistentes"],
      ["EDA", "explorar patrones iniciales mediante analisis descriptivo"],
      ["clasificacion", "predecir categorias discretas"],
      ["regresion", "predecir valores numericos continuos"],
      ["clustering", "agrupar datos similares sin etiquetas"],
      ["Apriori", "descubrir reglas de asociacion"],
      ["mineria de texto", "extraer informacion util desde documentos o mensajes"],
      ["datos geoespaciales", "analizar informacion vinculada a ubicaciones"],
    ],
    intermedio: [
      ["transformacion de datos", "preparar variables para mejorar el modelado"],
      ["discretizacion", "convertir valores continuos en intervalos"],
      ["Naive Bayes", "clasificar aplicando probabilidades condicionales"],
      ["arbol de decision", "dividir datos mediante reglas interpretables"],
      ["matriz de confusion", "comparar clases reales y predichas"],
      ["sensibilidad", "medir verdaderos positivos detectados"],
      ["especificidad", "medir verdaderos negativos detectados"],
      ["clustering jerarquico", "organizar observaciones en una estructura de niveles"],
      ["tokenizacion", "dividir texto en unidades analizables"],
      ["word cloud", "visualizar frecuencia de terminos relevantes"],
    ],
    dificil: [
      ["sobreajuste", "ajustar demasiado el ruido de entrenamiento"],
      ["validacion de modelos", "estimar desempeno fuera de los datos de entrenamiento"],
      ["reduccion de dimensionalidad", "conservar informacion con menos variables"],
      ["homogeneidad", "evaluar similitud interna de clusters"],
      ["separacion", "evaluar distancia entre grupos"],
      ["indice Jaccard", "medir similitud entre conjuntos"],
      ["analisis de sentimientos", "estimar polaridad emocional en textos"],
      ["web scraping", "extraer datos estructurables desde sitios web"],
      ["modelo raster", "representar espacio mediante celdas"],
      ["modelo vectorial", "representar entidades como puntos, lineas o poligonos"],
    ],
  },
  embebidos: {
    facil: [
      ["sistema embebido", "cumplir una funcion especifica dentro de un dispositivo"],
      ["microcontrolador", "integrar CPU, memoria y perifericos"],
      ["GPIO", "leer o escribir senales digitales generales"],
      ["sensor", "capturar magnitudes del entorno"],
      ["actuador", "ejecutar una accion fisica controlada"],
      ["software embebido", "controlar hardware bajo restricciones"],
      ["sistema operativo embebido", "administrar recursos en dispositivos limitados"],
      ["driver", "permitir comunicacion entre software y hardware"],
      ["Bluetooth", "comunicar dispositivos a corta distancia"],
      ["WiFi", "conectar dispositivos a redes locales inalambricas"],
    ],
    intermedio: [
      ["restricciones de energia", "optimizar autonomia en dispositivos alimentados por bateria"],
      ["arquitectura embebida", "organizar procesador, memoria, buses y perifericos"],
      ["interrupcion", "atender eventos asincronos de hardware"],
      ["temporizador", "medir intervalos o programar tareas periodicas"],
      ["UART", "comunicar dispositivos por enlace serial"],
      ["SPI", "interconectar perifericos con comunicacion sincronica"],
      ["I2C", "conectar multiples dispositivos con pocas lineas"],
      ["HDL", "describir circuitos digitales para simulacion o sintesis"],
      ["depuracion embebida", "observar fallos en interaccion hardware-software"],
      ["IoT", "conectar dispositivos fisicos a servicios de datos"],
    ],
    dificil: [
      ["tiempo real", "cumplir respuestas dentro de plazos definidos"],
      ["latencia de interrupcion", "medir demora entre evento y atencion"],
      ["consumo energetico", "balancear procesamiento, comunicacion y bateria"],
      ["simulacion de hardware", "validar comportamiento antes de implementacion fisica"],
      ["concurrencia embebida", "coordinar tareas, interrupciones y recursos compartidos"],
      ["firmware", "software cercano al hardware del dispositivo"],
      ["comunicacion de bajo poder", "elegir tecnologias para autonomia prolongada"],
      ["red celular embebida", "conectar dispositivos remotos con cobertura amplia"],
      ["monitoreo y control", "capturar datos y actuar sobre procesos fisicos"],
      ["robustez", "mantener operacion confiable ante fallos o ruido"],
    ],
  },
};

const subjectDistractors = {
  web: {
    facil: [
      "Definir unicamente colores, margenes y tipografias sin aportar estructura al contenido.",
      "Reemplazar la comunicacion cliente-servidor por archivos locales sin peticiones HTTP.",
      "Administrar versiones del repositorio sin intervenir en la ejecucion de la aplicacion.",
      "Ejecutar consultas de base de datos desde la vista sin separar responsabilidades.",
    ],
    intermedio: [
      "Convertir automaticamente cualquier aplicacion en un sistema distribuido tolerante a fallos.",
      "Eliminar la validacion del servidor porque el navegador ya proceso el formulario.",
      "Mezclar persistencia, interfaz y reglas de negocio en una sola capa para acelerar cambios.",
      "Evitar el control de versiones para que los despliegues sean mas simples.",
    ],
    dificil: [
      "Compartir la base de datos interna entre todos los servicios para evitar contratos de API.",
      "Priorizar la rapidez inicial aun cuando aumente el acoplamiento entre componentes.",
      "Desplegar sin pruebas automatizadas porque DevOps se limita a publicar archivos.",
      "Ignorar idempotencia y observabilidad mientras el endpoint responda en desarrollo.",
    ],
  },
  redes: {
    facil: [
      "Asignar nombres de variables a los paquetes sin modificar su transporte por la red.",
      "Documentar visualmente la topologia sin definir mecanismos de comunicacion o control.",
      "Eliminar el direccionamiento y confiar solo en la ubicacion fisica de los equipos.",
      "Sustituir la planificacion de capacidad por configuraciones aisladas en cada host.",
    ],
    intermedio: [
      "Configurar todos los equipos sin politicas de convergencia ni redundancia.",
      "Asignar la misma prioridad a voz, video y copias diferidas aunque tengan requisitos distintos.",
      "Resolver congestion aumentando etiquetas sin clasificar trafico ni medir retardo.",
      "Usar protocolos exteriores para reemplazar completamente el diseno de capa 2.",
    ],
    dificil: [
      "Redistribuir rutas sin filtros ni analisis de bucles o rutas suboptimas.",
      "Centralizar decisiones SDN sin considerar resiliencia del controlador.",
      "Aplicar QoS solo en un enlace aislado y asumir calidad extremo a extremo.",
      "Elegir un protocolo de enrutamiento por nombre, sin evaluar escala ni politicas.",
    ],
  },
  software: {
    facil: [
      "Escribir codigo inmediatamente sin analizar alcance, usuarios ni restricciones.",
      "Registrar solo nombres de funciones sin relacionarlos con necesidades del sistema.",
      "Elegir herramientas de programacion antes de comprender el problema del cliente.",
      "Reducir el proceso a pruebas al final, sin gestion ni documentacion previa.",
    ],
    intermedio: [
      "Aceptar requerimientos ambiguos porque el diseno posterior los resolvera por si solo.",
      "Eliminar criterios de aceptacion para que las historias de usuario sean mas flexibles.",
      "Separar el equipo del cliente durante todo el proyecto para evitar cambios.",
      "Codificar antes de validar alcance, restricciones y supuestos del producto.",
    ],
    dificil: [
      "Optimizar una decision local aunque deteriore mantenibilidad, trazabilidad y pruebas.",
      "Tratar verificacion y validacion como sinonimos sin evidencias diferentes.",
      "Resolver deuda tecnica agregando mas funcionalidades sin revisar estructura.",
      "Definir arquitectura solo al final, cuando el codigo ya impuso dependencias fuertes.",
    ],
  },
  mineria: {
    facil: [
      "Guardar datos en bruto sin seleccion, limpieza, transformacion ni interpretacion.",
      "Elegir un algoritmo antes de comprender variables, fuentes y calidad de datos.",
      "Presentar graficos descriptivos sin buscar patrones, relaciones o conocimiento util.",
      "Usar una metrica aislada sin relacionarla con el tipo de modelo evaluado.",
    ],
    intermedio: [
      "Entrenar modelos sin limpiar duplicados, ausentes o valores inconsistentes.",
      "Evaluar un clasificador solo con intuicion, sin matriz de confusion ni metricas.",
      "Aplicar clustering aunque exista una variable objetivo clara y etiquetada.",
      "Interpretar reglas de asociacion sin soporte, confianza ni contexto de negocio.",
    ],
    dificil: [
      "Seleccionar el modelo por mayor ajuste al entrenamiento sin validar generalizacion.",
      "Reducir dimensionalidad eliminando variables al azar sin analizar informacion perdida.",
      "Comparar clusters sin medir homogeneidad, separacion o similitud.",
      "Analizar sentimientos sin limpieza, tokenizacion ni control de stop words.",
    ],
  },
  embebidos: {
    facil: [
      "Ejecutar aplicaciones generales sin relacion directa con sensores, actuadores o perifericos.",
      "Depender de recursos ilimitados de procesamiento, memoria y energia.",
      "Separar completamente el software del comportamiento fisico del dispositivo.",
      "Usar hardware de proposito general sin restricciones temporales ni de consumo.",
    ],
    intermedio: [
      "Disenar el dispositivo sin considerar memoria, energia, tiempo de respuesta o perifericos.",
      "Atender eventos externos mediante espera activa permanente aunque consuma energia.",
      "Seleccionar comunicacion inalambrica solo por velocidad teorica, sin alcance ni bateria.",
      "Ignorar drivers porque el software embebido no interactua con hardware real.",
    ],
    dificil: [
      "Suponer que el tiempo real depende solo de que el procesador sea rapido.",
      "Compartir recursos entre interrupciones y tareas sin sincronizacion ni analisis de carrera.",
      "Validar firmware solo en simulacion aunque existan senales fisicas y ruido electrico.",
      "Elegir una tecnologia de bajo poder sin evaluar latencia, cobertura y tasa de datos.",
    ],
  },
};

const conceptUnits = {
  web: {
    "HTML semantico": 1,
    CSS: 1,
    JavaScript: 1,
    DOM: 1,
    "cliente-servidor": 2,
    "API REST": 2,
    MVC: 2,
    ORM: 2,
    "pruebas unitarias": 2,
    serverless: 2,
    "separacion de responsabilidades": 1,
    "validacion del lado cliente": 1,
    "controlador MVC": 2,
    SOA: 3,
    microservicios: 3,
    "estado de aplicacion": 3,
    "ramas Git": 4,
    "integracion continua": 4,
    "contratos REST": 2,
    "consistencia en microservicios": 3,
    "serverless computing": 2,
    "cobertura de pruebas": 2,
    "despliegue continuo": 4,
    observabilidad: 4,
    idempotencia: 3,
    "versionamiento semantico": 4,
    "seguridad de API": 2,
    "persistencia por servicio": 3,
    Git: 4,
    DevOps: 4,
  },
  redes: {
    "red inalambrica": 1,
    "punto de acceso": 1,
    "red movil": 2,
    MPLS: 2,
    SDN: 2,
    NFV: 2,
    OSPF: 3,
    STP: 3,
    BGP: 3,
    QoS: 4,
    interferencia: 1,
    "eficiencia espectral": 2,
    "ingenieria de trafico": 2,
    "controlador SDN": 2,
    "funciones virtualizadas": 2,
    "OSPF multi-area": 3,
    convergencia: 3,
    "eleccion STP": 3,
    "politicas BGP": 3,
    jitter: 4,
    "redistribucion de rutas": 3,
    "atributos BGP": 3,
    "QoS extremo a extremo": 4,
    "virtualizacion de red": 2,
    resiliencia: 3,
    latencia: 4,
    "planificacion de canales": 1,
    segmentacion: 1,
    "control distribuido": 2,
    "colas QoS": 4,
  },
  software: {
    "ingenieria de software": 1,
    "requerimiento funcional": 2,
    "requerimiento no funcional": 2,
    actor: 3,
    "caso de uso": 3,
    SRS: 2,
    Scrum: 4,
    "historia de usuario": 4,
    "diseno arquitectonico": 5,
    cohesion: 5,
    "alcance del producto": 2,
    trazabilidad: 2,
    "criterios de aceptacion": 4,
    backlog: 4,
    sprint: 4,
    "modelado de requerimientos": 3,
    prototipo: 3,
    acoplamiento: 5,
    "patrones de diseno": 5,
    mantenibilidad: 5,
    "ambiguedad de requerimientos": 2,
    "deuda tecnica": 5,
    "arquitectura evolutiva": 5,
    validacion: 3,
    verificacion: 3,
    "trade-off arquitectonico": 5,
    refactorizacion: 5,
    "gestion de cambios": 4,
    "diseno modular": 5,
    "calidad de software": 1,
  },
  mineria: {
    KDD: 1,
    "seleccion de datos": 1,
    "limpieza de datos": 1,
    EDA: 1,
    clasificacion: 2,
    regresion: 2,
    clustering: 3,
    Apriori: 3,
    "mineria de texto": 4,
    "datos geoespaciales": 4,
    "transformacion de datos": 1,
    discretizacion: 1,
    "Naive Bayes": 2,
    "arbol de decision": 2,
    "matriz de confusion": 2,
    sensibilidad: 2,
    especificidad: 2,
    "clustering jerarquico": 3,
    tokenizacion: 4,
    "word cloud": 4,
    sobreajuste: 2,
    "validacion de modelos": 2,
    "reduccion de dimensionalidad": 1,
    homogeneidad: 3,
    separacion: 3,
    "indice Jaccard": 3,
    "analisis de sentimientos": 4,
    "web scraping": 4,
    "modelo raster": 4,
    "modelo vectorial": 4,
  },
  embebidos: {
    "sistema embebido": 1,
    microcontrolador: 2,
    GPIO: 2,
    sensor: 1,
    actuador: 1,
    "software embebido": 3,
    "sistema operativo embebido": 3,
    driver: 3,
    Bluetooth: 4,
    WiFi: 4,
    "restricciones de energia": 1,
    "arquitectura embebida": 2,
    interrupcion: 3,
    temporizador: 3,
    UART: 2,
    SPI: 2,
    I2C: 2,
    HDL: 2,
    "depuracion embebida": 3,
    IoT: 4,
    "tiempo real": 3,
    "latencia de interrupcion": 3,
    "consumo energetico": 1,
    "simulacion de hardware": 2,
    "concurrencia embebida": 3,
    firmware: 3,
    "comunicacion de bajo poder": 4,
    "red celular embebida": 4,
    "monitoreo y control": 4,
    robustez: 1,
  },
};

const stems = {
  facil: [
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `${concept} cumple una funcion especifica en ${unitTitle.toLowerCase()}. Cual de las siguientes opciones describe mejor su utilidad?`,
      options: [
        `Un recurso utilizado para ${goal}.`,
        distractors[0],
        distractors[1],
        distractors[2],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `${concept} se aplica dentro de ${unitTitle.toLowerCase()} para resolver una necesidad concreta. Cual es su proposito principal?`,
      options: [
        `Facilitar ${goal}.`,
        distractors[1],
        distractors[2],
        distractors[3],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `Al trabajar con ${unitTitle.toLowerCase()}, en que situacion seria mas adecuado utilizar ${concept}?`,
      options: [
        `Cuando se requiere ${goal}.`,
        distractors[2],
        distractors[3],
        distractors[0],
      ],
    }),
  ],
  intermedio: [
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `En un proyecto academico relacionado con ${unitTitle.toLowerCase()}, se necesita tomar una decision tecnica sobre ${concept}. Que ventaja aporta aplicarlo correctamente?`,
      options: [
        `Permite ${goal} con mayor control y coherencia tecnica.`,
        distractors[0],
        distractors[1],
        distractors[2],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `Un equipo de trabajo necesita ${goal} y debe escoger una alternativa coherente con los contenidos de la unidad. Que papel cumple ${concept} en esa solucion?`,
      options: [
        "Aporta el mecanismo tecnico adecuado para resolver esa necesidad.",
        distractors[1],
        distractors[2],
        distractors[3],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `Al resolver un caso practico, no basta con definir ${concept}; tambien se debe justificar su uso. Que criterio demuestra una comprension adecuada?`,
      options: [
        `Relacionarlo con ${goal}, sin perder de vista el contexto y las restricciones del problema.`,
        distractors[2],
        distractors[3],
        distractors[0],
      ],
    }),
  ],
  dificil: [
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `En un escenario de analisis, se debe decidir si ${concept} es la alternativa mas conveniente para resolver un problema tecnico. Que criterio debe tener mayor peso en la decision?`,
      options: [
        `Su capacidad para ${goal}, considerando restricciones, riesgos y evidencia tecnica.`,
        distractors[0],
        distractors[1],
        distractors[2],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `Una implementacion deficiente de ${concept} puede generar fallos dificiles de corregir cuando la solucion crece. Que problema ayuda a prevenir una aplicacion correcta?`,
      options: [
        `La dificultad de ${goal} cuando el sistema crece o cambia.`,
        distractors[1],
        distractors[2],
        distractors[3],
      ],
    }),
    ({ concept, goal, subject, unitTitle, distractors }) => ({
      question: `Para responder una pregunta de mayor complejidad sobre ${concept}, se debe relacionar el concepto con sus consecuencias tecnicas. Cual afirmacion representa un analisis avanzado?`,
      options: [
        `Debe analizarse por su aporte a ${goal} y por su impacto en la solucion completa.`,
        distractors[2],
        distractors[3],
        distractors[0],
      ],
    }),
  ],
};

function buildSupplementalQuestions() {
  const generated = [];

  for (const subject of subjects) {
    for (const difficulty of Object.keys(difficultyLabels)) {
      const concepts = conceptMap[subject.id][difficulty];
      for (let index = 0; index < 30; index += 1) {
        const [concept, goal] = concepts[index % concepts.length];
        const unit = conceptUnits[subject.id][concept] ?? (index % subject.units.length) + 1;
        const unitTitle = subject.units[unit - 1];
        const distractors = subjectDistractors[subject.id][difficulty];
        const template = stems[difficulty][index % stems[difficulty].length];
        const built = template({ concept, goal, subject, unitTitle, distractors });

        generated.push({
          subjectId: subject.id,
          unit,
          difficulty,
          question: built.question,
          options: built.options,
          answer: 0,
          explanation: `La respuesta correcta se relaciona con ${goal}, que es el proposito tecnico asociado a ${concept} en la unidad "${unitTitle}". Las demas opciones describen usos incompletos o decisiones incorrectas para este contenido.`,
        });
      }
    }
  }

  return generated;
}

export const questionBank = [
  ...webQuestions,
  ...redesQuestions,
  ...softwareQuestions,
  ...mineriaQuestions,
  ...embebidosQuestions,
  ...buildSupplementalQuestions(),
];

export function getSubject(subjectId) {
  return subjects.find((subject) => subject.id === subjectId);
}
